updated workflow

diff --git a/.github/workflows/registry-actions.yml b/.github/workflows/registry-actions.yml
--- a/.github/workflows/registry-actions.yml
+++ b/.github/workflows/registry-actions.yml
@@ -62,6 +62,13 @@ jobs:
           sudo systemctl enable docker
           sudo systemctl is-active --quiet docker || sudo systemctl start docker
 
+      - name: Verify Docker Secrets
+        run: |
+          if [[ -z "${{ secrets.DOCKER_USERNAME }}" || -z "${{ secrets.DOCKER_PASSWORD }}" ]]; then
+            echo "ERROR: Docker credentials are missing! Set DOCKER_USERNAME and DOCKER_PASSWORD in repository secrets."
+            exit 1
+          fi
+
       - name: Log in to Docker Hub
         uses: docker/login-action@v3.2.0
         with:
@@ -100,13 +107,13 @@ jobs:
         env:
           USERNAME: ${{ secrets.DOCKER_USERNAME }}
         run: |
-            IMAGE="$(yq '.name' rockcraft.yaml)"
-            VERSION="$(yq '.version' rockcraft.yaml)"
-            ROCK="$(ls *.rock | tail -n 1)"
-            # Push to Docker Hub
-            sudo rockcraft.skopeo --insecure-policy copy oci-archive:"${ROCK}" docker-daemon:"${USERNAME}/${IMAGE}:${VERSION}-stable"
-            docker push ${USERNAME}/${IMAGE}:${VERSION}-stable
-            # Push to GitHub Packages
-            GITHUB_IMAGE="ghcr.io/${{ github.repository_owner }}/${IMAGE}"
-            docker tag ${USERNAME}/${IMAGE}:${VERSION}-stable ${GITHUB_IMAGE}:${VERSION}-stable
-            docker push ${GITHUB_IMAGE}:${VERSION}-stable
+          IMAGE="$(yq '.name' rockcraft.yaml)"
+          VERSION="$(yq '.version' rockcraft.yaml)"
+          ROCK="$(ls *.rock | tail -n 1)"
+          # Push to Docker Hub
+          sudo rockcraft.skopeo --insecure-policy copy oci-archive:"${ROCK}" docker-daemon:"${USERNAME}/${IMAGE}:${VERSION}-stable"
+          docker push ${USERNAME}/${IMAGE}:${VERSION}-stable
+          # Push to GitHub Packages
+          GITHUB_IMAGE="ghcr.io/${{ github.repository_owner }}/${IMAGE}"
+          docker tag ${USERNAME}/${IMAGE}:${VERSION}-stable ${GITHUB_IMAGE}:${VERSION}-stable
+          docker push ${GITHUB_IMAGE}:${VERSION}-stable
